### ISSUE TITLE
No Contents to display inline message should be shown to the user when there are no contents under reported, removed and ignored list. 

### ISSUE THREAD

**Issue by Sivanagarjuna** [bombinatetech/dashboard-topics#3]
Pre-Condition:
1. Launch the Spam website.
2. No contents should be present under any of the list.
Steps:
1. Select From and To dates.
2. Select any of the list in type.
3. Click on Submit button.
4. Verify the inline message.
Actual Result: Inline message is not displaying.
Expected Result: No Contents to display inline message should be shown to the user when there are no contents under reported, removed and ignored list.

**Comment by yatender-oktalk** [comment]
resolved
